export const GET_PRODUCTS = 'get_products'
export const GET_ORDERS = 'get_orders'
export const ORDER_DATA_SUCCESS = 'SEARCH_ORDERS_SUCCESS'
export const ORDER_DATA_HAS_ERRORED = 'ORDER_DATA_HAS_ERRORED'
export const ORDER_DATA_IS_LOADING = 'ORDER_DATA_IS_LOADING'
export const ORDER_DATA_DETAIL_SUCCESS = 'GET_ORDER_DETAIL'
export const ORDERS_DATA_DETAIL_SUCCESS = 'ORDERS_DATA_DETAIL_SUCCESS'
export const PRODUCT_DATA_HAS_ERRORED = 'PRODUCT_DATA_HAS_ERRORED'
export const PRODUCT_DATA_IS_LOADING = 'PRODUCT_DATA_IS_LOADING'
export const PRODUCT_UPDATE_DATA_SUCCESS = 'PRODUCT_UPDATE_DATA_SUCCESS'
export const ORDERS_UPDATE_DATA_SUCCESS = 'ORDERS_UPDATE_DATA_SUCCESS'
export const INVOICE_GET_DATA_SUCCESS = 'INVOICE_GET_DATA_SUCCESS'
export const INVOICE_DATA_HAS_ERRORED = 'INVOICE_DATA_HAS_ERRORED'
export const INVOICE_DATA_IS_LOADING = 'INVOICE_DATA_IS_LOADING'
export const INVOICE_CREATE_PDF_SUCCESS = 'INVOICE_CREATE_PDF_SUCCESS'
export const SEARCH_ORDER_DATA_IS_LOADING = 'SEARCH_ORDER_DATA_IS_LOADING'
export const ORDERS_WITHOUT_INVOICE_GET_SUCCESS = 'ORDERS_WITHOUT_INVOICE_GET_SUCCESS'
export const ORDER_DATA_ITEM_IS_LOADING = 'ORDER_DATA_ITEM_IS_LOADING'
export const SHIPPING_UPLOAD_SUCCESS = 'SHIPPING_UPLOAD_SUCCESS'
export const SHIPPING_DATA_HAS_ERRORED = 'SHIPPING_DATA_HAS_ERRORED'
export const SHIPPING_DATA_IS_LOADING = 'SHIPPING_DATA_IS_LOADING'
export const SHIPPING_UPDATE_SUCCESS = 'SHIPPING_UPDATE_SUCCESS'

export const ORDERS_FILTER_SUCCESS = 'ORDERS_FILTER_SUCCESS'
export const GET_PARAMETERS_SUCCESS = 'GET_PARAMETERS_SUCCESS'
export const SET_PARAMETERS_SUCCESS = 'SET_PARAMETERS_SUCCESS'
export const PARAMETERS_ERROR = 'PARAMETERS_ERROR'

export const AUTH_USER = 'auth_user';
export const UNAUTH_USER = 'unauth_user';
export const AUTH_ERROR = 'auth_error';
export const FETCH_MESSAGE = 'fetch_message';
export const AUTH_RESULT = 'AUTH_RESULT';
export const INVOICE_SET_STYLE_SUCCESS = 'INVOICE_SET_STYLE_SUCCESS';
export const INVOICE_GET_STYLE_SUCCESS = 'INVOICE_GET_STYLE_SUCCESS';
export const INIT_INVOICE = 'INIT_INVOICE';
export const ORDERS_ARCHIVE_DETAIL_SUCCESS = 'ORDERS_ARCHIVE_DETAIL_SUCCESS';
export const ARCHIVE_ORDER_SUCCESS = 'ARCHIVE_ORDER_SUCCESS';

export const INITIALIZE_ARCHIVE_DATA = 'INITIALIZE_ARCHIVE_DATA';

export const ADD_INVOICE_SUCCESS = 'ADD_INVOICE_SUCCESS';
export const GET_INVOICE_SUCCESS = 'GET_INVOICE_SUCCESS';


export const PARAMETER_DATA_IS_LOADING = 'PARAMETER_DATA_IS_LOADING';
export const ORDERS_DATA_DETAIL_COUNT_SUCCESS = 'ORDERS_DATA_DETAIL_COUNT_SUCCESS';
export const ORDERSN11_DATA_DETAIL_SUCCESS = 'ORDERSN11_DATA_DETAIL_SUCCESS';
export const ORDERSN11_DATA_DETAIL_FAIL = 'ORDERSN11_DATA_DETAIL_FAIL';


export const INVOICE_GET_LIST_DATA_SUCCESS = 'INVOICE_GET_LIST_DATA_SUCCESS';






